// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.DbContexts;

#nullable disable

namespace WebApi.Repo.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250424165652_M2MCreatingCollection")]
    partial class M2MCreatingCollection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DiretorFilme", b =>
                {
                    b.Property<int>("DiretoresId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FilmesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiretoresId", "FilmesId");

                    b.HasIndex("FilmesId");

                    b.ToTable("DiretorFilme");
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Diretor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diretores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Martin Scorsese"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Greta Gerwig"
                        });
                });

            modelBuilder.Entity("WebApi.Domain.Entities.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2010,
                            Titulo = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2014,
                            Titulo = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            Ano = 1993,
                            Titulo = "Jurassic Park"
                        },
                        new
                        {
                            Id = 4,
                            Ano = 1982,
                            Titulo = "E.T. the Extra-Terrestrial"
                        },
                        new
                        {
                            Id = 5,
                            Ano = 2013,
                            Titulo = "The Wolf of Wall Street"
                        },
                        new
                        {
                            Id = 6,
                            Ano = 2010,
                            Titulo = "Shutter Island"
                        },
                        new
                        {
                            Id = 7,
                            Ano = 1994,
                            Titulo = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 8,
                            Ano = 2019,
                            Titulo = "Once Upon a Time in Hollywood"
                        },
                        new
                        {
                            Id = 9,
                            Ano = 2017,
                            Titulo = "Lady Bird"
                        },
                        new
                        {
                            Id = 10,
                            Ano = 2023,
                            Titulo = "Barbie"
                        });
                });

            modelBuilder.Entity("DiretorFilme", b =>
                {
                    b.HasOne("WebApi.Domain.Entities.Diretor", null)
                        .WithMany()
                        .HasForeignKey("DiretoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Domain.Entities.Filme", null)
                        .WithMany()
                        .HasForeignKey("FilmesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
