// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.DbContexts;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250414175942_AdicionarDadosIniciais")]
    partial class AdicionarDadosIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("WebApi.Entities.Diretor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Diretores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Christopher Nolan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Steven Spielberg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Martin Scorsese"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Quentin Tarantino"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Greta Gerwig"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Filme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiretorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiretorId");

                    b.ToTable("Filmes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ano = 2010,
                            DiretorId = 1,
                            Titulo = "Inception"
                        },
                        new
                        {
                            Id = 2,
                            Ano = 2014,
                            DiretorId = 1,
                            Titulo = "Interstellar"
                        },
                        new
                        {
                            Id = 3,
                            Ano = 1993,
                            DiretorId = 2,
                            Titulo = "Jurassic Park"
                        },
                        new
                        {
                            Id = 4,
                            Ano = 1982,
                            DiretorId = 2,
                            Titulo = "E.T. the Extra-Terrestrial"
                        },
                        new
                        {
                            Id = 5,
                            Ano = 2013,
                            DiretorId = 3,
                            Titulo = "The Wolf of Wall Street"
                        },
                        new
                        {
                            Id = 6,
                            Ano = 2010,
                            DiretorId = 3,
                            Titulo = "Shutter Island"
                        },
                        new
                        {
                            Id = 7,
                            Ano = 1994,
                            DiretorId = 4,
                            Titulo = "Pulp Fiction"
                        },
                        new
                        {
                            Id = 8,
                            Ano = 2019,
                            DiretorId = 4,
                            Titulo = "Once Upon a Time in Hollywood"
                        },
                        new
                        {
                            Id = 9,
                            Ano = 2017,
                            DiretorId = 5,
                            Titulo = "Lady Bird"
                        },
                        new
                        {
                            Id = 10,
                            Ano = 2023,
                            DiretorId = 5,
                            Titulo = "Barbie"
                        });
                });

            modelBuilder.Entity("WebApi.Entities.Filme", b =>
                {
                    b.HasOne("WebApi.Entities.Diretor", "Diretor")
                        .WithMany("Filmes")
                        .HasForeignKey("DiretorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diretor");
                });

            modelBuilder.Entity("WebApi.Entities.Diretor", b =>
                {
                    b.Navigation("Filmes");
                });
#pragma warning restore 612, 618
        }
    }
}
